---
title: "범죄유형별 검거까지의 기간 분석 프로젝트"
author: "Jisu Kang"
date: "2022-12-05"
output: html_document
---

이창훈. (2014). 범죄 발생에서 해결까지: 경찰의 범죄해결 신속성과 관련된 요인 연구. 한국범죄학, 8(2), 97-144.
신원부, 이원희. (2020). 범죄유형별 평균 검거 소요일수 측정에 관한 연구. 한국경찰학회보, 22(2), 107-126.

```{r include=FALSE}
library(tidyverse)
library(survival)
library(KMsurv)
library(ggplot2)
library(interval)
library(data.table)
```

1. 데이터 전처리
```{r}
#데이터 불러오기
crime <- read.csv("범죄발생부터_검거까지의_기간.csv", fileEncoding = "euc-kr")
crime.all <- read.csv("범죄의_발생_검거상황_총괄.csv", fileEncoding = "euc-kr")


#데이터 정리
colnames(crime) <- as.character(crime[1,])
crime <- crime[-1,]
crime[1:3] <- lapply(crime[1:3], as.factor)
crime[4:13] <- lapply(crime[4:13], as.integer)
crime[is.na(crime)]<-0
colnames(crime)[1:4] <- c("crime1", "crime2", "crime3","cases")
head(crime)

#전체 범죄수 포함 - 행 고르기
colnames(crime.all) <- as.character(crime.all[1,])
crime.all <- crime.all[-1,]
crime.all <- crime.all[crime.all$`범죄별(4)` == "소계",c(1:3,5:8)]
crime.all[1,1]<-"합계"
crime.all[1:3] <- lapply(crime.all[1:3], as.factor)
crime.all[c(4,6)] <- lapply(crime.all[c(4,6)], as.integer)
crime.all[c(5,7)] <- lapply(crime.all[c(5,7)], as.double)
crime.all[is.na(crime.all)]<-0
colnames(crime.all) <- c("crime1", "crime2", "crime3",
                         "cases_all","ratio10","cases","ratio")

crime_full <- inner_join(crime, crime.all, 
                         by = c("crime1", "crime2", "crime3", "cases"))
crime_full <- subset(crime_full, crime1 != "특별법범")
head(crime_full)

#subset
crime.sub <- subset(crime_full, select = -c(cases_all, ratio10,ratio))
head(crime.sub)

crime.sum <- subset(crime_full, crime3 == "소계", select = -crime3)
head(crime.sum)
crime.id <- subset(crime_full, crime3 != "소계")
head(crime.id)
```

2. EDA : 형법범만 보기
```{r}
ratio <- subset(crime.id, crime2 != "소계", select = c("crime2", "crime3", "ratio"))
ratio.sub <- subset(crime.sum[3:10,], select = c("crime1", "crime2", "ratio"))

check_outlier <- function(v, coef=1.5){
  quantiles <- quantile(v,probs=c(0.25,0.75))
  IQR <- quantiles[2]-quantiles[1]
  res <- v < (quantiles[1]-coef*IQR)|v > (quantiles[2]+coef*IQR)
  return(res)
}

ratio <- data.table(ratio)
ratio[,outlier:=check_outlier(ratio), by=crime2]
ratio[,label:= crime3]
ratio[outlier == F, label:= ""]

#plot
ggplot()+
  geom_histogram(subset(crime.sum, crime2 != "소계"), 
                 mapping = aes(x = crime2, y = ratio), stat="identity", 
                 fill = "salmon", alpha = 0.6) +
  geom_boxplot(ratio,mapping = aes(x = crime2, y=ratio))+
  geom_text(ratio,mapping = aes(x = crime2, y=ratio, label=label),hjust=-0.3)+
  geom_text(subset(crime.sum, crime2 != "소계"), 
            mapping = aes(x = crime2, y = 2, label = paste0(ratio, "%")), 
            hjust = "inward", size = 3)+
  coord_flip() +
  labs(y = "발생건수대비 검거건수 (%)",
       x = "범죄 유형", 
       title = "범죄 유형별 발생건수대비 검거율")

#재산범죄
ggplot(subset(crime.id, crime2 %in% c("재산범죄", "위조범죄"))) +
  geom_histogram(aes(x = crime3, y = ratio, fill = crime2), 
                 stat="identity") +
  geom_text(aes(x = crime3, y = 2, label = paste0(ratio, "%"), hjust = "inward"))+
  coord_flip() +
  labs(y = "발생건수대비 검거건수 (%)",
       x = "범죄 유형", 
       title = "위조범죄와 재산범죄 유형별 발생건수대비 검거율")
#강력범죄(흉악)
ggplot(subset(crime.id, crime2 %in% c("강력범죄(폭력)", "강력범죄(흉악)"))) +
  geom_histogram(aes(x = crime3, y = ratio, fill = crime2), 
                 stat="identity") +
  geom_text(aes(x = crime3, y = 2, label = paste0(ratio, "%"), hjust = "inward"))+
  coord_flip() +
  labs(y = "발생건수대비 검거건수 (%)",
       x = "강력범죄 범죄 유형", 
       title = "강력범죄 유형별 발생건수대비 검거율")

```

3. 전체 survival function - crime2
```{r}
total <- subset(crime.sub, crime1 == "합계", select = -c(crime1, crime2, crime3))
total <- total %>% gather(colnames(total)[2:10], key = "time", value = "cases")
total
total <- total %>%
  mutate(left = ifelse(time == "1일 이내", 0, 
                  ifelse(time == "2일 이내", 1,
                    ifelse(time == "3일 이내", 2,
                      ifelse(time == "10일 이내", 4,
                        ifelse(time == "1개월 이내", 11,
                          ifelse(time == "3개월 이내", 31,
                            ifelse(time == "6개월 이내", 93,
                              ifelse(time == "1년 이내", 184,
                                ifelse(time == "1년 초과", 366, NA))))))))),
         right = ifelse(time == "1일 이내", 1, 
                  ifelse(time == "2일 이내", 2,
                    ifelse(time == "3일 이내", 3,
                      ifelse(time == "10일 이내", 10,
                        ifelse(time == "1개월 이내", 30,
                          ifelse(time == "3개월 이내", 92,
                            ifelse(time == "6개월 이내", 183,
                              ifelse(time == "1년 이내", 365,
                                ifelse(time == "1년 초과", Inf, NA))))))))))
total <- data.table(total)

total.expanded <- total[,list(freq=rep(1,cases)), by=c("left","right")]
total.expanded[ ,freq := NULL]

surv.c <- Surv(total.expanded$left, total.expanded$right, type = "interval2")
table(surv.c)
surv.fit <- icfit(surv.c~1)
summary(surv.fit)
plot(surv.fit, main = "범죄 발생부터 검거까지의 기간")
```

4. 범죄별 2 function 재산범죄, 강력범죄 위조범죄 공무원범죄 비교
```{r}
df <- subset(crime.sum, 
             crime2 %in% c("재산범죄", "강력범죄(흉악)", 
                           "강력범죄(폭력)", "위조범죄", "공무원범죄"),
             select = -c(crime1, cases_all, ratio10, ratio))

df <- df %>% gather(colnames(df)[3:11], 
                    key = "time", value = "cases")

df <- df %>%
    mutate(left = ifelse(time == "1일 이내", 0, 
                   ifelse(time == "2일 이내", 1,
                      ifelse(time == "3일 이내", 2,
                        ifelse(time == "10일 이내", 4,
                          ifelse(time == "1개월 이내", 11,
                            ifelse(time == "3개월 이내", 31,
                              ifelse(time == "6개월 이내", 93,
                                ifelse(time == "1년 이내", 184,
                                  ifelse(time == "1년 초과", 366, NA))))))))),
           right = ifelse(time == "1일 이내", 1, 
                    ifelse(time == "2일 이내", 2,
                      ifelse(time == "3일 이내", 3,
                        ifelse(time == "10일 이내", 10,
                          ifelse(time == "1개월 이내", 30,
                            ifelse(time == "3개월 이내", 92,
                              ifelse(time == "6개월 이내", 183,
                                ifelse(time == "1년 이내", 365,
                                  ifelse(time == "1년 초과", Inf, NA))))))))))
df <- data.table(df)

df.expanded <- df[,list(freq=rep(1,cases)), by=c("crime2","left","right")]
df.expanded[ ,freq := NULL]
fit_1 <- icfit(Surv(left, right, type = "interval2")~crime2, data = df.expanded)
summary(fit_1)
plot(fit_1, shade = F, XLEG = 200, YLEG = 1, LTY = c(1:3, 5, 6),
     main = "범죄유형별 범죄 발생부터 검거까지의 기간")
plot(fit_1, shade = F, XLEG = 0, YLEG = 0.5, LTY = c(1:3, 5, 6), 
     xlim = c(0,30), ylim = c(0.2, 1),
     main = "범죄유형별 범죄 발생부터 검거까지의 기간 (~30일)")

df.expanded.1 <-df.expanded
df.expanded.1$crime2 <- factor(df.expanded.1$crime2)
df.expanded.1$left <- df.expanded.1$left+1
df.expanded.1$right <- df.expanded.1$right+1
sreg <- survreg(Surv(left, right, type = "interval2")~crime2, 
                dist = "exponential", data = df.expanded.1)


summary(sreg)
```

5. 폭력 흉악 위조 재산 공무원
폭력
```{r}
df <- subset(crime.id, 
             crime2 == "강력범죄(폭력)",
             select = -c(crime1,crime2, cases_all, ratio10, ratio))

df <- df %>% gather(colnames(df)[3:11], 
                    key = "time", value = "cases")

df <- df %>%
    mutate(left = ifelse(time == "1일 이내", 0, 
                   ifelse(time == "2일 이내", 1,
                      ifelse(time == "3일 이내", 2,
                        ifelse(time == "10일 이내", 4,
                          ifelse(time == "1개월 이내", 11,
                            ifelse(time == "3개월 이내", 31,
                              ifelse(time == "6개월 이내", 93,
                                ifelse(time == "1년 이내", 184,
                                  ifelse(time == "1년 초과", 366, NA))))))))),
           right = ifelse(time == "1일 이내", 1, 
                    ifelse(time == "2일 이내", 2,
                      ifelse(time == "3일 이내", 3,
                        ifelse(time == "10일 이내", 10,
                          ifelse(time == "1개월 이내", 30,
                            ifelse(time == "3개월 이내", 92,
                              ifelse(time == "6개월 이내", 183,
                                ifelse(time == "1년 이내", 365,
                                  ifelse(time == "1년 초과", Inf, NA))))))))))
df <- data.table(df)

df.expanded1 <- df[,list(freq=rep(1,cases)),
                   by=c("crime3","left","right")]
df.expanded1[ ,freq := NULL]
fit1_1 <- icfit(Surv(left, right, type = "interval2")~crime3, 
                data = df.expanded1)
summary(fit1_1)
plot(fit1_1, shade = F, XLEG = 150, YLEG = 1, LTY = c(1:3, 5, 6),
     main = "강력범죄(폭력) 유형별 범죄 발생부터 검거까지의 기간")
plot(fit1_1, shade = F, XLEG = 0, YLEG = 0.5, LTY = c(1:3, 5, 6), 
     xlim = c(0,30), ylim = c(0.2, 1),
     main = "강력범죄(폭력) 유형별 범죄 발생부터 검거까지의 기간 (~30일)")

df.expanded1.1 <-df.expanded1
df.expanded1.1$crime3 <- factor(df.expanded1.1$crime3)
df.expanded1.1$left <- df.expanded1$left+1
df.expanded1.1$right <- df.expanded1$right+1

sreg <- survreg(Surv(left, right, type = "interval2")~crime3, 
                dist = "exponential", data = df.expanded1.1)


summary(sreg)
```
흉악
```{r}
df <- subset(crime.id, 
             crime2 == "강력범죄(흉악)",
             select = -c(crime1,crime2, cases_all, ratio10, ratio))

df <- df %>% gather(colnames(df)[3:11], 
                    key = "time", value = "cases")

df <- df %>%
    mutate(left = ifelse(time == "1일 이내", 0, 
                   ifelse(time == "2일 이내", 1,
                      ifelse(time == "3일 이내", 2,
                        ifelse(time == "10일 이내", 4,
                          ifelse(time == "1개월 이내", 11,
                            ifelse(time == "3개월 이내", 31,
                              ifelse(time == "6개월 이내", 93,
                                ifelse(time == "1년 이내", 184,
                                  ifelse(time == "1년 초과", 366, NA))))))))),
           right = ifelse(time == "1일 이내", 1, 
                    ifelse(time == "2일 이내", 2,
                      ifelse(time == "3일 이내", 3,
                        ifelse(time == "10일 이내", 10,
                          ifelse(time == "1개월 이내", 30,
                            ifelse(time == "3개월 이내", 92,
                              ifelse(time == "6개월 이내", 183,
                                ifelse(time == "1년 이내", 365,
                                  ifelse(time == "1년 초과", Inf, NA))))))))))
df <- data.table(df)

df.expanded2 <- df[,list(freq=rep(1,cases)),
                  by=c("crime3","left","right")]
df.expanded2[ ,freq := NULL]
fit1_2 <- icfit(Surv(left, right, type = "interval2")~crime3, 
                data = df.expanded2)
summary(fit1_2)
plot(fit1_2, shade = F, XLEG = 250, YLEG = 1, LTY = c(1:3, 5),
     main = "강력범죄(흉악) 유형별 범죄 발생부터 검거까지의 기간")
plot(fit1_2, shade = F, XLEG = 20, YLEG = 1, LTY = c(1:3, 5), 
     xlim = c(0,30), ylim = c(0.2, 1),
     main = "강력범죄(흉악) 유형별 범죄 발생부터 검거까지의 기간 (~30일)")

df.expanded2.1 <-df.expanded2
df.expanded2.1$crime3 <- factor(df.expanded2.1$crime3)
df.expanded2.1$left <- df.expanded2.1$left+1
df.expanded2.1$right <- df.expanded2.1$right+1

sreg <- survreg(Surv(left, right, type = "interval2")~crime3, 
                dist = "exponential", data = df.expanded2.1)


summary(sreg)
```
위조
```{r}
df <- subset(crime.id, 
             crime2 == "위조범죄",
             select = -c(crime1,crime2, cases_all, ratio10, ratio))

df <- df %>% gather(colnames(df)[3:11], 
                    key = "time", value = "cases")

df <- df %>%
    mutate(left = ifelse(time == "1일 이내", 0, 
                   ifelse(time == "2일 이내", 1,
                      ifelse(time == "3일 이내", 2,
                        ifelse(time == "10일 이내", 4,
                          ifelse(time == "1개월 이내", 11,
                            ifelse(time == "3개월 이내", 31,
                              ifelse(time == "6개월 이내", 93,
                                ifelse(time == "1년 이내", 184,
                                  ifelse(time == "1년 초과", 366, NA))))))))),
           right = ifelse(time == "1일 이내", 1, 
                    ifelse(time == "2일 이내", 2,
                      ifelse(time == "3일 이내", 3,
                        ifelse(time == "10일 이내", 10,
                          ifelse(time == "1개월 이내", 30,
                            ifelse(time == "3개월 이내", 92,
                              ifelse(time == "6개월 이내", 183,
                                ifelse(time == "1년 이내", 365,
                                  ifelse(time == "1년 초과", Inf, NA))))))))))
df <- data.table(df)

df.expanded3 <- df[,list(freq=rep(1,cases)),
                   by=c("crime3","left","right")]
df.expanded3[ ,freq := NULL]
fit1_3 <- icfit(Surv(left, right, type = "interval2")~crime3, 
                data = df.expanded3)
summary(fit1_3)
plot(fit1_3, shade = F, XLEG = 220, YLEG = 1.05,
     main = "위조범죄 유형별 범죄 발생부터 검거까지의 기간")
plot(fit1_3, shade = F, XLEG = 0, YLEG = 0.5, 
     xlim = c(0,30), ylim = c(0.2, 1),
     main = "위조범죄 유형별 범죄 발생부터 검거까지의 기간 (~30일)")

df.expanded3.1 <-df.expanded3
df.expanded3.1$crime3 <- factor(df.expanded3.1$crime3)
df.expanded3.1$left <- df.expanded3.1$left+1
df.expanded3.1$right <- df.expanded3.1$right+1

sreg <- survreg(Surv(left, right, type = "interval2")~crime3, 
                dist = "exponential", data = df.expanded3.1)


summary(sreg)
```
재산
```{r}
df <- subset(crime.id, 
             crime2 == "재산범죄",
             select = -c(crime1,crime2, cases_all, ratio10, ratio))

df <- df %>% gather(colnames(df)[3:11], 
                    key = "time", value = "cases")

df <- df %>%
    mutate(left = ifelse(time == "1일 이내", 0, 
                   ifelse(time == "2일 이내", 1,
                      ifelse(time == "3일 이내", 2,
                        ifelse(time == "10일 이내", 4,
                          ifelse(time == "1개월 이내", 11,
                            ifelse(time == "3개월 이내", 31,
                              ifelse(time == "6개월 이내", 93,
                                ifelse(time == "1년 이내", 184,
                                  ifelse(time == "1년 초과", 366, NA))))))))),
           right = ifelse(time == "1일 이내", 1, 
                    ifelse(time == "2일 이내", 2,
                      ifelse(time == "3일 이내", 3,
                        ifelse(time == "10일 이내", 10,
                          ifelse(time == "1개월 이내", 30,
                            ifelse(time == "3개월 이내", 92,
                              ifelse(time == "6개월 이내", 183,
                                ifelse(time == "1년 이내", 365,
                                  ifelse(time == "1년 초과", Inf, NA))))))))))
df <- data.table(df)

df.expanded4 <- df[,list(freq=rep(1,cases)),
                  by=c("crime3","left","right")]
df.expanded4[ ,freq := NULL]
fit1_4 <- icfit(Surv(left, right, type = "interval2")~crime3, 
                data = df.expanded4)
summary(fit1_4)
plot(fit1_4, shade = F, XLEG = 250, YLEG = 1.05,
     main = "재산범죄 유형별 범죄 발생부터 검거까지의 기간")
plot(fit1_4, shade = F, XLEG = 0, YLEG = 0.6, 
     xlim = c(0,30), ylim = c(0.2, 1),
     main = "재산범죄 유형별 범죄 발생부터 검거까지의 기간 (~30일)")

df.expanded4.1 <-df.expanded4
df.expanded4.1$crime3 <- factor(df.expanded4.1$crime3)
df.expanded4.1$left <- df.expanded4.1$left+1
df.expanded4.1$right <- df.expanded4.1$right+1

sreg <- survreg(Surv(left, right, type = "interval2")~crime3, 
                dist = "exponential", data = df.expanded4.1)


summary(sreg)
```
공무원
```{r}
df <- subset(crime.id, 
             crime2 == "공무원범죄",
             select = -c(crime1,crime2, cases_all, ratio10, ratio))

df <- df %>% gather(colnames(df)[3:11], 
                    key = "time", value = "cases")

df <- df %>%
    mutate(left = ifelse(time == "1일 이내", 0, 
                   ifelse(time == "2일 이내", 1,
                      ifelse(time == "3일 이내", 2,
                        ifelse(time == "10일 이내", 4,
                          ifelse(time == "1개월 이내", 11,
                            ifelse(time == "3개월 이내", 31,
                              ifelse(time == "6개월 이내", 93,
                                ifelse(time == "1년 이내", 184,
                                  ifelse(time == "1년 초과", 366, NA))))))))),
           right = ifelse(time == "1일 이내", 1, 
                    ifelse(time == "2일 이내", 2,
                      ifelse(time == "3일 이내", 3,
                        ifelse(time == "10일 이내", 10,
                          ifelse(time == "1개월 이내", 30,
                            ifelse(time == "3개월 이내", 92,
                              ifelse(time == "6개월 이내", 183,
                                ifelse(time == "1년 이내", 365,
                                  ifelse(time == "1년 초과", Inf, NA))))))))))
df <- data.table(df)

df.expanded5 <- df[,list(freq=rep(1,cases)),
                  by=c("crime3","left","right")]
df.expanded5[ ,freq := NULL]
fit1_5 <- icfit(Surv(left, right, type = "interval2")~crime3, 
                data = df.expanded5)
summary(fit1_5)
plot(fit1_5, shade = F, XLEG = 0, YLEG = 0.4, 
     main = "공무원범죄 유형별 범죄 발생부터 검거까지의 기간")
plot(fit1_5, shade = F, XLEG = 0, YLEG = 0.8, 
     xlim = c(0,30), ylim = c(0.7, 1),
     main = "공무원범죄 유형별 범죄 발생부터 검거까지의 기간 (~30일)")

df.expanded5.1 <-df.expanded5
df.expanded5.1$crime3 <- factor(df.expanded5.1$crime3)
df.expanded5.1$left <- df.expanded5.1$left+1
df.expanded5.1$right <- df.expanded5.1$right+1

sreg <- survreg(Surv(left, right, type = "interval2")~crime3, 
                dist = "exponential", data = df.expanded5.1)


summary(sreg)
```
6. 전체 곡선과 유형별 곡선 비교
```{r}
test_1<- ictest(Surv(left, right, type = "interval2")~crime2, 
                data = df.expanded)
test1_1 <- ictest(Surv(left, right, type = "interval2")~crime3,
                  data = df.expanded1)
test1_2 <- ictest(Surv(left, right, type = "interval2")~crime3,
                  data = df.expanded2)
test1_3 <- ictest(Surv(left, right, type = "interval2")~crime3,
                  data = df.expanded3)
test1_4 <- ictest(Surv(left, right, type = "interval2")~crime3,
                  data = df.expanded4)
test1_5 <- ictest(Surv(left, right, type = "interval2")~crime3,
                  data = df.expanded5)
test_1
test1_1
test1_2
test1_3
test1_4
test1_5
```

